### ISSUE TITLE
Auto-restart dask-worker sidecar

### ISSUE THREAD

**Issue by bbockelm** [CoffeaTeam/jhub#31]
When I use the `dask-labextension` to shutdown a cluster, I believe it also shuts down the `dask-worker` process and hence the sidecar.

I see this in the output of `kubectl get pods`:

```
jupyter-brian-2ebockelman-40cern-2ech   1/2     NotReady   0          5m22s
```

And indeed the `dask-worker` sidecar says this in `kubectl describe pods`:

```
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Fri, 13 Nov 2020 10:37:13 -0600
      Finished:     Fri, 13 Nov 2020 10:40:36 -0600
```

Can we tinker with the container so `dask-worker` runs under supervisord and auto-restarts?

This is high-priority as when the pod goes into `NotReady` state it appears `traefik` stops passing new requests and things begin to lock up.

**Comment by bbockelm** [comment]
Talking with @oshadura this morning, we think this might be one of the remaining reasons why the UI is stalling.

**Comment by oshadura** [comment]
Still waiting to confirm closing after tests
